// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto.proto

It has these top-level messages:
	CreateThingOneOfRequest
	CreateThingOneOfResponse
	CreateThingAnyRequest
	CreateThingAnyResponse
	Thing
	Error
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_Reserved ErrorCode = 0
	ErrorCode_One      ErrorCode = 1
	ErrorCode_Two      ErrorCode = 2
	ErrorCode_Three    ErrorCode = 3
)

var ErrorCode_name = map[int32]string{
	0: "Reserved",
	1: "One",
	2: "Two",
	3: "Three",
}
var ErrorCode_value = map[string]int32{
	"Reserved": 0,
	"One":      1,
	"Two":      2,
	"Three":    3,
}

func (x ErrorCode) String() string {
	return proto1.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateThingOneOfRequest struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *CreateThingOneOfRequest) Reset()                    { *m = CreateThingOneOfRequest{} }
func (m *CreateThingOneOfRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateThingOneOfRequest) ProtoMessage()               {}
func (*CreateThingOneOfRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateThingOneOfRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateThingOneOfResponse struct {
	// Types that are valid to be assigned to Result:
	//	*CreateThingOneOfResponse_Thing
	//	*CreateThingOneOfResponse_Error
	Result isCreateThingOneOfResponse_Result `protobuf_oneof:"Result"`
}

func (m *CreateThingOneOfResponse) Reset()                    { *m = CreateThingOneOfResponse{} }
func (m *CreateThingOneOfResponse) String() string            { return proto1.CompactTextString(m) }
func (*CreateThingOneOfResponse) ProtoMessage()               {}
func (*CreateThingOneOfResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isCreateThingOneOfResponse_Result interface {
	isCreateThingOneOfResponse_Result()
}

type CreateThingOneOfResponse_Thing struct {
	Thing *Thing `protobuf:"bytes,1,opt,name=Thing,oneof"`
}
type CreateThingOneOfResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=Error,oneof"`
}

func (*CreateThingOneOfResponse_Thing) isCreateThingOneOfResponse_Result() {}
func (*CreateThingOneOfResponse_Error) isCreateThingOneOfResponse_Result() {}

func (m *CreateThingOneOfResponse) GetResult() isCreateThingOneOfResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateThingOneOfResponse) GetThing() *Thing {
	if x, ok := m.GetResult().(*CreateThingOneOfResponse_Thing); ok {
		return x.Thing
	}
	return nil
}

func (m *CreateThingOneOfResponse) GetError() *Error {
	if x, ok := m.GetResult().(*CreateThingOneOfResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateThingOneOfResponse) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _CreateThingOneOfResponse_OneofMarshaler, _CreateThingOneOfResponse_OneofUnmarshaler, _CreateThingOneOfResponse_OneofSizer, []interface{}{
		(*CreateThingOneOfResponse_Thing)(nil),
		(*CreateThingOneOfResponse_Error)(nil),
	}
}

func _CreateThingOneOfResponse_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*CreateThingOneOfResponse)
	// Result
	switch x := m.Result.(type) {
	case *CreateThingOneOfResponse_Thing:
		b.EncodeVarint(1<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Thing); err != nil {
			return err
		}
	case *CreateThingOneOfResponse_Error:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CreateThingOneOfResponse.Result has unexpected type %T", x)
	}
	return nil
}

func _CreateThingOneOfResponse_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*CreateThingOneOfResponse)
	switch tag {
	case 1: // Result.Thing
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(Thing)
		err := b.DecodeMessage(msg)
		m.Result = &CreateThingOneOfResponse_Thing{msg}
		return true, err
	case 2: // Result.Error
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Result = &CreateThingOneOfResponse_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CreateThingOneOfResponse_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*CreateThingOneOfResponse)
	// Result
	switch x := m.Result.(type) {
	case *CreateThingOneOfResponse_Thing:
		s := proto1.Size(x.Thing)
		n += proto1.SizeVarint(1<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *CreateThingOneOfResponse_Error:
		s := proto1.Size(x.Error)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateThingAnyRequest struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *CreateThingAnyRequest) Reset()                    { *m = CreateThingAnyRequest{} }
func (m *CreateThingAnyRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateThingAnyRequest) ProtoMessage()               {}
func (*CreateThingAnyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateThingAnyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateThingAnyResponse struct {
	Result *google_protobuf.Any `protobuf:"bytes,2,opt,name=Result" json:"Result,omitempty"`
}

func (m *CreateThingAnyResponse) Reset()                    { *m = CreateThingAnyResponse{} }
func (m *CreateThingAnyResponse) String() string            { return proto1.CompactTextString(m) }
func (*CreateThingAnyResponse) ProtoMessage()               {}
func (*CreateThingAnyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateThingAnyResponse) GetResult() *google_protobuf.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

type Thing struct {
	ID   string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *Thing) Reset()                    { *m = Thing{} }
func (m *Thing) String() string            { return proto1.CompactTextString(m) }
func (*Thing) ProtoMessage()               {}
func (*Thing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Thing) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Error struct {
	Code    ErrorCode         `protobuf:"varint,1,opt,name=Code,enum=ErrorCode" json:"Code,omitempty"`
	Message string            `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	Service string            `protobuf:"bytes,3,opt,name=Service" json:"Service,omitempty"`
	Details map[string]string `protobuf:"bytes,4,rep,name=Details" json:"Details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto1.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Error) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_Reserved
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Error) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto1.RegisterType((*CreateThingOneOfRequest)(nil), "CreateThingOneOfRequest")
	proto1.RegisterType((*CreateThingOneOfResponse)(nil), "CreateThingOneOfResponse")
	proto1.RegisterType((*CreateThingAnyRequest)(nil), "CreateThingAnyRequest")
	proto1.RegisterType((*CreateThingAnyResponse)(nil), "CreateThingAnyResponse")
	proto1.RegisterType((*Thing)(nil), "Thing")
	proto1.RegisterType((*Error)(nil), "Error")
	proto1.RegisterEnum("ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto1.RegisterFile("proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xdb, 0xae, 0xd2, 0x40,
	0x14, 0xed, 0x85, 0x03, 0x87, 0xcd, 0x09, 0x69, 0xc6, 0xe3, 0x39, 0xa5, 0x0f, 0x84, 0xf4, 0x89,
	0xa8, 0x0c, 0x49, 0x4d, 0x8c, 0xe1, 0x4d, 0x01, 0x23, 0x0f, 0x4a, 0x52, 0xf9, 0x81, 0x22, 0x9b,
	0x4a, 0xac, 0x1d, 0x9c, 0x69, 0x31, 0xfd, 0x14, 0x7f, 0xc8, 0xef, 0x32, 0x73, 0x29, 0x22, 0x82,
	0x2f, 0xcd, 0x5e, 0x7b, 0xed, 0xce, 0x5a, 0xfb, 0x02, 0x9d, 0x3d, 0x67, 0x05, 0xa3, 0xea, 0x1b,
	0xf4, 0x52, 0xc6, 0xd2, 0x0c, 0xc7, 0x0a, 0xad, 0xcb, 0xed, 0x38, 0xc9, 0x2b, 0x4d, 0x85, 0x23,
	0x78, 0x9c, 0x72, 0x4c, 0x0a, 0x5c, 0x7d, 0xd9, 0xe5, 0xe9, 0x32, 0xc7, 0xe5, 0x36, 0xc6, 0xef,
	0x25, 0x8a, 0x82, 0x10, 0x68, 0x7c, 0x4c, 0xbe, 0xa1, 0x6f, 0x0f, 0xec, 0x61, 0x3b, 0x56, 0x71,
	0xb8, 0x01, 0xff, 0xdf, 0x72, 0xb1, 0x67, 0xb9, 0x40, 0xd2, 0x87, 0x1b, 0x95, 0x55, 0x3f, 0x74,
	0xa2, 0x26, 0x55, 0xe8, 0xbd, 0x15, 0xeb, 0xb4, 0xe4, 0xe7, 0x9c, 0x33, 0xee, 0x3b, 0x86, 0x57,
	0x48, 0xf2, 0x2a, 0x78, 0x7b, 0x0b, 0xcd, 0x18, 0x45, 0x99, 0x15, 0xe1, 0x73, 0x78, 0x7a, 0xa2,
	0xf2, 0x26, 0xaf, 0xfe, 0x67, 0xe9, 0x1d, 0x3c, 0x9c, 0x17, 0x1b, 0x43, 0x2f, 0xea, 0x07, 0x8d,
	0xe2, 0x3d, 0xd5, 0x73, 0xa0, 0xf5, 0x1c, 0xa8, 0xac, 0xfe, 0x23, 0x6a, 0x7c, 0x76, 0xc1, 0x59,
	0xcc, 0x8c, 0x84, 0xb3, 0x98, 0x1d, 0x45, 0x9d, 0x13, 0xd1, 0x5f, 0xb6, 0x69, 0x86, 0xf4, 0xa1,
	0x31, 0x65, 0x1b, 0x6d, 0xa9, 0x1b, 0x81, 0x6e, 0x4a, 0x66, 0x62, 0x95, 0x27, 0x3e, 0xb4, 0x3e,
	0xa0, 0x10, 0x49, 0x5a, 0x3f, 0x50, 0x43, 0xc9, 0x7c, 0x42, 0x7e, 0xd8, 0x7d, 0x46, 0xdf, 0xd5,
	0x8c, 0x81, 0x64, 0x04, 0xad, 0x19, 0x16, 0xc9, 0x2e, 0x13, 0x7e, 0x63, 0xe0, 0x0e, 0x3b, 0xd1,
	0x13, 0xfd, 0x2c, 0x35, 0xd9, 0x79, 0x5e, 0xf0, 0x2a, 0xae, 0x6b, 0x82, 0x09, 0xdc, 0x9d, 0x12,
	0xc4, 0x03, 0xf7, 0x2b, 0x56, 0xa6, 0x03, 0x19, 0x92, 0x7b, 0xb8, 0x39, 0x24, 0x59, 0x59, 0x5b,
	0xd0, 0x60, 0xe2, 0xbc, 0xb6, 0x9f, 0xbd, 0x82, 0xf6, 0xd1, 0x31, 0xb9, 0x83, 0xdb, 0x18, 0x05,
	0xf2, 0x03, 0x6e, 0x3c, 0x8b, 0xb4, 0xc0, 0x5d, 0xe6, 0xe8, 0xd9, 0x32, 0x58, 0xfd, 0x60, 0x9e,
	0x43, 0xda, 0x72, 0x44, 0x1c, 0xd1, 0x73, 0xa3, 0x9f, 0xf6, 0xd1, 0x3d, 0x59, 0x80, 0x77, 0x7e,
	0x14, 0xc4, 0xa7, 0x57, 0xce, 0x2a, 0xe8, 0xd1, 0x6b, 0x17, 0x14, 0x5a, 0x64, 0x0a, 0xdd, 0xbf,
	0x97, 0x49, 0x1e, 0xe8, 0xc5, 0x53, 0x08, 0x1e, 0xe9, 0xe5, 0xad, 0x87, 0xd6, 0xba, 0xa9, 0xf6,
	0xfb, 0xf2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x81, 0x53, 0x41, 0x04, 0x03, 0x00, 0x00,
}
