// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto.proto

It has these top-level messages:
	CreateThingOneOfRequest
	CreateThingOneOfResponse
	CreateThingAnyRequest
	CreateThingAnyResponse
	Thing
	Error
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Service service

type Service interface {
	CreateThingOneOf(ctx context.Context, in *CreateThingOneOfRequest, opts ...client.CallOption) (*CreateThingOneOfResponse, error)
	CreateThingAny(ctx context.Context, in *CreateThingAnyRequest, opts ...client.CallOption) (*CreateThingAnyResponse, error)
}

type service struct {
	c    client.Client
	name string
}

func NewService(name string, c client.Client) Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "service"
	}
	return &service{
		c:    c,
		name: name,
	}
}

func (c *service) CreateThingOneOf(ctx context.Context, in *CreateThingOneOfRequest, opts ...client.CallOption) (*CreateThingOneOfResponse, error) {
	req := c.c.NewRequest(c.name, "Service.CreateThingOneOf", in)
	out := new(CreateThingOneOfResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) CreateThingAny(ctx context.Context, in *CreateThingAnyRequest, opts ...client.CallOption) (*CreateThingAnyResponse, error) {
	req := c.c.NewRequest(c.name, "Service.CreateThingAny", in)
	out := new(CreateThingAnyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceHandler interface {
	CreateThingOneOf(context.Context, *CreateThingOneOfRequest, *CreateThingOneOfResponse) error
	CreateThingAny(context.Context, *CreateThingAnyRequest, *CreateThingAnyResponse) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) {
	type service interface {
		CreateThingOneOf(ctx context.Context, in *CreateThingOneOfRequest, out *CreateThingOneOfResponse) error
		CreateThingAny(ctx context.Context, in *CreateThingAnyRequest, out *CreateThingAnyResponse) error
	}
	type Service struct {
		service
	}
	h := &serviceHandler{hdlr}
	s.Handle(s.NewHandler(&Service{h}, opts...))
}

type serviceHandler struct {
	ServiceHandler
}

func (h *serviceHandler) CreateThingOneOf(ctx context.Context, in *CreateThingOneOfRequest, out *CreateThingOneOfResponse) error {
	return h.ServiceHandler.CreateThingOneOf(ctx, in, out)
}

func (h *serviceHandler) CreateThingAny(ctx context.Context, in *CreateThingAnyRequest, out *CreateThingAnyResponse) error {
	return h.ServiceHandler.CreateThingAny(ctx, in, out)
}
